export default [
  {
    id: 11,
    image: "topMoist1.jpg",
    title: "Lakme",
    description: "Skin Brightening Night Creme",
    price: "288",
    orprice: "525",
    category: "Moisturizer",
  },

  {
    id: 12,
    image: "topcleanser1.jpg",
    title: "Minimalist",
    description: "Salicylic Face Wash",
    price: "284",
    orprice: "299",
    category: "Cleanser",
  },
  {
    id: 13,
    image: "topsunscreen1.jpg",
    title: "Lakme",
    description: "Ultra Matte SPF 50 Sunscreen",
    price: "219",
    orprice: "365",
    category: "Sunscreen",
  },
  {
    id: 14,
    image: "topfaceserum.jpg",
    title: "minimalist",
    description: "Minimalist 2% Alpha Arbutin Serum",
    price: "521",
    orprice: "549",
    category: "FaceSerum",
  },
  {
    id: 15,
    image: "topserum1.jpg",
    title: "Streax Professional",
    description: "Vitariche Hair Serum 200ml",
    price: "356",
    orprice: "475",
    category: "HairSerum",
  },

  {
    id: 16,
    image: "topshamp1.jpg",
    title: "LOreal",
    description: "Hyaluron Shampoo-340 ml",
    price: "300",
    orprice: "429",
    category: "Shampoo",
  },
  {
    id: 17,
    image: "topcond1.jpg",
    title: "TRESemme",
    description: "Hyaluronic COnditioner-370 ml",
    price: "384",
    orprice: "549",
    category: "Conditioner",
  },
  {
    id: 18,
    image: "topoil1.jpg",
    title: "Parachute",
    description: "JAsmine Gold Hair Oil 300 ml",
    price: "95",
    orprice: "164",
    category: "HairOil",
  },
  {
    id: 19,
    image: "tophairgel1.jpg",
    title: "Livon",
    description: "Style Pro Styling Gel-100 ml",
    price: "399",
    orprice: "665",
    category: "HairGel",
  },
  {
    id: 20,
    image: "moist1.jpg",
    title: "Neutrogena",
    description: "Neutrogena Hydro Boost Moisturizer 50ml",
    price: "1012",
    orprice: "1150",
    category: "Moisturizer",
  },
  {
    id: 21,
    image: "moist2.jpg",
    title: "Plum",
    description: "plum 2% Niacinamide 50g Moisturizer",
    price: "472",
    orprice: "525",
    category: "Moisturizer",
  },
  {
    id: 22,
    image: "moist3.jpg",
    title: "Dr.Sheth's",
    description: "Dr Sheth's Ceramide & vitamin C 50g Moisturizer",
    price: "303",
    orprice: "349",
    category: "Moisturizer",
  },
  {
    id: 23,
    image: "moist4.jpg",
    title: "Biotique",
    description: "Biotique Morning Nectar Moisturizer 190ml",
    price: "204",
    orprice: "330",
    category: "Moisturizer",
  },
  {
    id: 24,
    image: "moist5.jpg",
    title: "derma",
    description: "The Derma Co oil-Free Daily Face Moisturizer 100g",
    price: "313",
    orprice: "349",
    category: "Moisturizer",
  },
  {
    id: 25,
    image: "moist6.jpg",
    title: "mamaearth",
    description: "Mamaearth Vitamin C ultra Oil-free Moisturizer 200ml",
    price: "306",
    orprice: "349",
    category: "Moisturizer",
  },
  {
    id: 26,
    image: "moist7.jpg",
    title: "Nivea",
    description: "NIVEA Soft Light Moisturizer 300ml",
    price: "268",
    orprice: "465",
    category: "Moisturizer",
  },
  {
    id: 27,
    image: "moist8.jpg",
    title: "Dot & Key",
    description: "Dot & Key 72HR hydrating gel+probiotics Moisturizer 60ml",
    price: "430",
    orprice: "495",
    category: "Moisturizer",
  },
  {
    id: 28,
    image: "moist9.jpg",
    title: "Rice Ceramide",
    description: "The face shop rice & ceramide moisturizing Emulsion 150ml",
    price: "820",
    orprice: "890",
    category: "Moisturizer",
  },
  {
    id: 29,
    image: "moist10.jpg",
    title: "La Shield",
    description: "La shield probiotic Moisturizer Face Cream 50g",
    price: "199",
    orprice: "399",
    category: "Moisturizer",
  },
  {
    id: 30,
    image: "cleanser1.jpg",
    title: "Neutrogena",
    description: "Deep clean Gentle Facial Cleanser 200ml",
    price: "446",
    orprice: "525",
    category: "Cleanser",
  },
  {
    id: 31,
    image: "Cleanser2.jpg",
    title: "Cetaphil",
    description: "Oily Skin Cleanser,Gentle Foaming 125ml",
    price: "636",
    orprice: "649",
    category: "Cleanser",
  },
  {
    id: 32,
    image: "Cleanser3.jpg",
    title: "Neutrogena",
    description: "Deep Clean Foaming Cleanser,50g",
    price: "166",
    orprice: "175",
    category: "Cleanser",
  },
  {
    id: 33,
    image: "sunscreen1.jpg",
    title: "The Man",
    description: "Oil free sunscreen gel 50 PA+++ for Men 50gm",
    price: "399",
    orprice: "599",
    category: "Sunscreen",
  },
  {
    id: 34,
    image: "sunscreen2.jpg",
    title: "Aqualogica",
    description: "Glow+ Dewy LightWeight & Hydrating Sunscreen",
    price: "526",
    orprice: "599",
    category: "Sunscreen",
  },
  {
    id: 35,
    image: "sunscreen3.jpg",
    title: "Neutrogena",
    description: "Ultra sheer sunscreen,No white cast ,30g",
    price: "227",
    orprice: "260",
    category: "Sunscreen",
  },

  {
    id: 36,
    image: "faceserum1.jpg",
    title: "Plum",
    description: "15% vitamin c Face serum for glowing skin",
    price: "200",
    orprice: "299",
    category: "FaceSerum",
  },
  {
    id: 37,
    image: "faceserum2.jpg",
    title: "The Derma Co",
    description: "10% Niacinamide Face serum for Acne prone skin,10ml",
    price: "223",
    orprice: "249",
    category: "FaceSerum",
  },
  {
    id: 38,
    image: "faceserum3.jpg",
    title: "L'Oreal Paris",
    description: "Instant Glowing Serum 1% Glycolic Acid,30ml",
    price: "749",
    orprice: "850",
    category: "FaceSerum",
  },
  {
    id: 39,
    image: "hairserum1.jpg",
    title: "L'Oreal Paris",
    description: "Protect and shine,flyway 30ml",
    price: "209",
    orprice: "299",
    category: "HairSerum",
  },
  {
    id: 40,
    image: "hairserum2.jpg",
    title: "Biolage",
    description: "Smoothproof 6-in-1 Natural & vegan",
    price: "279",
    orprice: "325",
    category: "HairSerum",
  },
  {
    id: 41,
    image: "hairserum3.jpg",
    title: "pilgrim Redensyl",
    description: " 3% + Anagain 4% Hair Growth serum (50ml)",
    price: "670",
    orprice: "895",
    category: "HairSerum",
  },
  {
    id: 42,
    image: "shampoo1.jpg",
    title: "L'OREAL",
    description: "Absolute Repair Shampoo For Damaged Hair",
    price: "598",
    orprice: "665",
    category: "Shampoo",
  },
  {
    id: 43,
    image: "shampoo2.jpg",
    title: "Tresemme",
    description: "Keratin Smooth ,1L For Straighter hair",
    price: "798",
    orprice: "1150",
    category: "Shampoo",
  },
  {
    id: 44,
    image: "shampoo3.jpg",
    title: "Herbal Essences",
    description: "For Frizz Free,Soft Hair,400ml",
    price: "342",
    orprice: "659",
    category: "Shampoo",
  },

  {
    id: 45,
    image: "conditioner1.jpg",
    title: "Clensta",
    description: "Eggstreme Hair Conditionerwith Biotin,Egg Protein 250ml",
    price: "314",
    orprice: "349",
    category: "Conditioner",
  },
  {
    id: 46,
    image: "conditioner2.jpg",
    title: "Botanic Hearth",
    description: "Keratin Conditioner with Collagen 245ml",
    price: "275",
    orprice: "325",
    category: "Conditioner",
  },
  {
    id: 47,
    image: "conditioner3.jpg",
    title: "Maxisoft",
    description: "Healthy & Silky Smooth Hair 100ml",
    price: "342",
    orprice: "659",
    category: "Conditioner",
  },
  {
    id: 48,
    image: "hairoil1.jpg",
    title: "Botonic Hearth",
    description: "Tea Tree Oil for Hair with Argan,jojoba",
    price: "340",
    orprice: "425",
    category: "HairOil",
  },
  {
    id: 49,
    image: "hairoil2.jpg",
    title: "Soulflower",
    description: "Rosemary Lavender Hair oil",
    price: "348",
    orprice: "400",
    category: "HairOil",
  },
  {
    id: 50,
    image: "hairoil3.jpg",
    title: "Emami",
    description: "7 Oils in One Non Sticky Hair Oil,500ml",
    price: "150",
    orprice: "305",
    category: "HairOil",
  },
  {
    id: 51,
    image: "hairgel1.jpg",
    title: "Fix my curls",
    description: "ENriched with sunflower oil & kertain",
    price: "353",
    orprice: "380",
    category: "HairGel",
  },
  {
    id: 52,
    image: "hairgel2.jpg",
    title: "Arata",
    description: "Styling Hair Gel(50ml) for all Hair Types",
    price: "209",
    orprice: "299",
    category: "HairGel",
  },
  {
    id: 53,
    image: "hairgel3.jpg",
    title: "Enn",
    description: "Re-Flex Flax Seed HAir Styling Gel (100 ml)",
    price: "349",
    orprice: "490",
    category: "HairGel",
  },
];
